-- lua configuration files
require('plugins-config/cmp')
require('plugins-config/closetag')
require('plugins-config/easy-align')
require('plugins-config/indent-line')
require('plugins-config/nvim-tree')
require('plugins-config/telescope')
require('plugins-config/treesitter')
require('plugins-config/session-manager')
require('plugins-config/lualine')
require('plugins-config/gitsigns')
require('plugins-config/colorizer')
