vim.o.linespace = 7
vim.o.number = true
vim.o.relativenumber = true
vim.o.numberwidth = 1
vim.o.showtabline = 2
vim.o.guifont = 'FiraMono'
vim.o.scrolloff = 5
vim.o.cursorline = true
vim.o.undofile = true
vim.o.tabstop = 2
vim.o.shiftwidth = 2
vim.o.expandtab = true
vim.o.switchbuf = 'usetab'
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.inccommand = 'nosplit' -- enable live substitution on neovim
vim.o.conceallevel = 0
vim.o.clipboard = 'unnamedplus'
vim.o.updatetime = 50
vim.o.termguicolors = true -- required by plugins like bufferline.nvim
vim.o.wrap = false
vim.o.signcolumn = 'yes:2'
vim.o.sessionoptions = 'blank,buffers,curdir,help,tabpages,winsize,terminal' -- default: blank,buffers,curdir,folds,help,tabpages,winsize,terminal
vim.o.ignorecase = true
vim.g.node_host_prog = '~/.nvm/versions/node/v22.14.0/lib/node_modules'
